spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: gulimall-search
  thymeleaf:
    cache: false
  redis:
    host: 192.168.23.134
  session:
    store-type: redis


server:
  port: 13000